[[03/26/2019 06:56:50 AM]] Internal Server Error: /textdocument/
Traceback (most recent call last):
  File "/home/hina/Music/Django/AnalogPen/venv/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/hina/Music/Django/AnalogPen/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/hina/Music/Django/AnalogPen/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hina/Music/Django/AnalogPen/home/views.py", line 17, in doc_text
    demo.generateDoc()
  File "/home/hina/Music/Django/handwriting-synthesis/demo.py", line 189, in generateDoc
    styles=styles,
  File "/home/hina/Music/Django/handwriting-synthesis/demo.py", line 62, in write
    self._draw(strokes, lines, filename, stroke_colors=stroke_colors, stroke_widths=stroke_widths)
  File "/home/hina/Music/Django/handwriting-synthesis/demo.py", line 149, in _draw
    dwg.save()
  File "/home/hina/Music/Django/AnalogPen/venv/lib/python3.4/site-packages/svgwrite/drawing.py", line 116, in save
    fileobj = io.open(self.filename, mode='w', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: 'img/usage_demo2.svg'
